apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-k8s
  labels:
    app: kafka-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-k8s
  template:
    metadata:
      labels:
        app: kafka-k8s
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              name: broker
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-k8s:9092,EXTERNAL://localhost:29092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
