name: Destroy Infrastructure (Admin Only)

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Run destroy.sh (restricted)
    runs-on: ubuntu-latest

    steps:
      - name: Restrict to organization admins
        run: |
          echo "Triggered by: ${{ github.actor }}"
          case "${{ github.actor }}" in
            maksym-panov)
              echo "✅ Authorized admin"
              ;;
            *)
              echo "⛔ Access denied: ${{ github.actor }} is not allowed to run destroy"
              exit 1
              ;;
          esac

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Run destroy.sh
        run: ./destroy.sh
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          DEPLOYER_ARN: ${{ secrets.DEPLOYER_ARN }}
          ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
          ROUTE_53_ZONE_ID: ${{ secrets.ROUTE_53_ZONE_ID }}
          SYSTEM_TOKEN: ${{ secrets.SYSTEM_TOKEN }}
          SECRET_ARN: ${{ secrets.AUTH_SERVICE_SECRET_ARN }}
